apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -o src/kubernetes/kompose/
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-core
  name: nginx-core
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-core
    spec:
      containers:
      - image: gpupo/container-orchestration:nginx-core-latest
        name: nginx-core
        resources: {}
      restartPolicy: Always
status: {}
