apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -o src/kubernetes/kompose/
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_USER
        image: gpupo/container-orchestration:rabbitmq-latest
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15671
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
status: {}
