version: '3'
services:
    debian:
        container_name: debian
        # build:
        #     context: ./src/images/debian/
        image: gpupo/container-orchestration
        env_file:
            - .env

    nginx-wordpress:
        container_name: nginx-wordpress
        build:
            context: ./src/images/nginx-wordpress/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:nginx-wordpress-${CO_VERSION}
        env_file:
            - .env

    nodejs-dev:
        container_name: nodejs-dev
        build:
            context: ./src/images/nodejs-dev/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:nodejs-dev-${CO_VERSION}
        env_file:
            - .env
    ruby-dev:
        container_name: ruby-dev
        build:
            context: ./src/images/ruby-dev/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:ruby-dev-${CO_VERSION}
        env_file:
            - .env

    python-dev:
        container_name: python
        build:
            context: ./src/images/python-dev/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:python-dev-${CO_VERSION}
        env_file:
            - .env

    jekyll:
        container_name: jekyll
        build:
            context: ./src/images/jekyll/
            args:
              CO_VERSION: ${CO_VERSION}
              JEKYLL_VERSION: ${JEKYLL_VERSION}
        image: gpupo/container-orchestration:jekyll-${CO_VERSION}

    elasticsearch:
        container_name: elasticsearch
        build:
            context: ./src/images/elasticsearch/
            args:
              CO_VERSION: ${CO_VERSION}
              ELK_VERSION: ${ELK_VERSION}
        image: gpupo/container-orchestration:elasticsearch-${CO_VERSION}
        env_file:
            - .env

    logstash:
        container_name: logstash
        build:
            context: ./src/images/logstash/
            args:
              CO_VERSION: ${CO_VERSION}
              ELK_VERSION: ${ELK_VERSION}
        image: gpupo/container-orchestration:logstash-${CO_VERSION}
        env_file:
            - .env

    kibana:
        container_name: kibana
        build:
            context: ./src/images/kibana/
            args:
              CO_VERSION: ${CO_VERSION}
              ELK_VERSION: ${ELK_VERSION}
        image: gpupo/container-orchestration:kibana-${CO_VERSION}
        env_file:
            - .env

    rabbitmq:
        container_name: rabbitmq
        build:
            context: ./src/images/rabbitmq/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:rabbitmq-${CO_VERSION}
        env_file:
            - .env
