version: '3'
services:
    php:
        # container_name: php-fpm
        build:
            context: ./src/images/php-fpm/
        image: container-orchestration/php-fpm:latest
        ports:
            - "9000:9000"
        volumes:
            - ./shared/app:/var/www/app
            - ./shared/log/app:/var/www/app/var/logs
    nginx:
        # container_name: nginx
        build:
            context: ./src/images/nginx/
        image: container-orchestration/nginx:latest
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./shared/log/nginx:/var/logs/nginx
            - ./shared/app:/var/www/app
