version: '3'
services:
    php:
        container_name: php
        build:
            context: ./src/images/php-fpm/
        image: gpupo/container-orchestration:php-latest
        ports:
            - "9000:9000"
        volumes:
            - ./shared/app:/var/www/app
            - ./shared/log/app:/var/www/app/var/logs
        networks:
            - backend
    nginx:
        container_name: nginx
        build:
            context: ./src/images/nginx/
        image: gpupo/container-orchestration:nginx-latest
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./shared/log/nginx:/var/logs/nginx
            - ./shared/app:/var/www/app
        networks:
            - frontend
            - backend

    mariadb:
        container_name: mariadb
        build:
            context: ./src/images/mariadb/
        image: gpupo/container-orchestration:mariadb-latest
        ports:
            - "3306:3306"
        volumes:
            - ./shared/mariadb:/var/lib/mysql
        networks:
            - frontend
            - backend
        environment:
            - MYSQL_DATABASE=${MARIADB_DATABASE}
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

    elk:
        container_name: elk
        build:
            context: ./src/images/elk/
        image: gpupo/container-orchestration:elk-latest
        ports:
            - "8080:80"
        volumes:
            - ./shared/elk/logstash:/etc/logstash
            - ./shared/elk/logstash/patterns:/opt/logstash/patterns
        networks:
            - frontend
            - backend
    jackrabbit:
        container_name: jackrabbit
        build:
            context: ./src/images/jackrabbit/
        image: gpupo/container-orchestration:jackrabbit-latest
        ports:
            - "8081:8080"
        links:
            - rabbitmq
        environment:
            RABBIT_URL: 'amqp://rabbitmq'

    rabbitmq:
        container_name: rabbitmq
        build:
            context: ./src/images/rabbitmq/
        image: gpupo/container-orchestration:rabbitmq-latest
        ports:
            - "5672:5672"
            - "15672:15672"
            - "15671:15671"
        privileged: true
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        depends_on:
            - php
        networks:
            - backend

networks:
    frontend:
    backend:
