version: '3'

volumes:
    mariadb-data:
        driver: ${VOLUMES_DRIVER}
    app-data:
        driver: ${VOLUMES_DRIVER}
    logs-data:
        driver: ${VOLUMES_DRIVER}

services:
    php:
        container_name: php
        build:
            context: ./src/images/php-fpm/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:php-fpm-${CO_VERSION}
        ports:
            - "9000:9000"
        volumes:
            - app-data:/var/www/app
        networks:
            - backend
    php-dev:
        container_name: php-dev
        build:
            context: ./src/images/php-dev/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:php-dev-${CO_VERSION}
    nodejs-dev:
        container_name: nodejs-dev
        build:
            context: ./src/images/nodejs-dev/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:nodejs-dev-${CO_VERSION}

    python-dev:
        container_name: python
        build:
            context: ./src/images/python-dev/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:python-dev-${CO_VERSION}

    nginx-core:
        container_name: nginx-core
        build:
            context: ./src/images/nginx-core/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:nginx-core-${CO_VERSION}

    nginx-upstream:
        container_name: nginx-upstream
        build:
            context: ./src/images/nginx-upstream/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:nginx-upstream-${CO_VERSION}
        depends_on:
          - nginx-core
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - logs-data:/var/logs/nginx
            - app-data:/var/www/app
        networks:
            - frontend
            - backend

    nginx-wordpress:
        container_name: nginx-wordpress
        build:
            context: ./src/images/nginx-wordpress/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:nginx-wordpress-${CO_VERSION}


    # simpleHTTPServer:
    #     container_name: simpleHTTPServer
    #     build:
    #         context: ./src/images/simpleHTTPServer/
    #         args:
    #           CO_VERSION: ${CO_VERSION}
    #     image: gpupo/container-orchestration:simpleHTTPServer-${CO_VERSION}
    debian:
        container_name: debian
        build:
            context: ./src/images/debian/
        image: gpupo/container-orchestration:debian-${CO_VERSION}
    # mariadb:
    #     container_name: mariadb
    #     build:
    #         context: ./src/images/mariadb/
    #     image: gpupo/container-orchestration:mariadb-${CO_VERSION}
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - mariadb-data:/var/lib/mysql
    #     networks:
    #         - frontend
    #         - backend
    #     environment:
    #         - MYSQL_DATABASE=${MARIADB_DATABASE}
    #         - MYSQL_USER=${MARIADB_USER}
    #         - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    #         - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    #
    elasticsearch:
        container_name: elasticsearch
        build:
            context: ./src/images/elasticsearch/
            args:
              CO_VERSION: ${CO_VERSION}
              ELK_VERSION: ${ELK_VERSION}
        image: gpupo/container-orchestration:elasticsearch-${CO_VERSION}
    logstash:
        container_name: logstash
        build:
            context: ./src/images/logstash/
            args:
              CO_VERSION: ${CO_VERSION}
              ELK_VERSION: ${ELK_VERSION}
        image: gpupo/container-orchestration:logstash-${CO_VERSION}

    kibana:
        container_name: kibana
        build:
            context: ./src/images/kibana/
            args:
              CO_VERSION: ${CO_VERSION}
              ELK_VERSION: ${ELK_VERSION}
        image: gpupo/container-orchestration:kibana-${CO_VERSION}

    # jackrabbit:
    #     container_name: jackrabbit
    #     build:
    #         context: ./src/images/jackrabbit/
    #     image: gpupo/container-orchestration:jackrabbit-${CO_VERSION}
    #     ports:
    #         - "8081:8080"
    #     links:
    #         - rabbitmq
    #     environment:
    #         RABBIT_URL: 'amqp://rabbitmq'
    #
    rabbitmq:
        container_name: rabbitmq
        build:
            context: ./src/images/rabbitmq/
            args:
              CO_VERSION: ${CO_VERSION}
        image: gpupo/container-orchestration:rabbitmq-${CO_VERSION}


networks:
    frontend:
    backend:
