version: '3'
services:
    php:
        container_name: php
        build:
            context: ./src/images/php-fpm/
        image: gpupo/container-orchestration:php-latest
        ports:
            - "9000:9000"
        volumes:
            - ./shared/app:/var/www/app
            - ./shared/log/app:/var/www/app/var/logs
        networks:
            - backend
    nginx:
        container_name: nginx
        build:
            context: ./src/images/nginx/
        image: gpupo/container-orchestration:nginx-latest
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./shared/log/nginx:/var/logs/nginx
            - ./shared/app:/var/www/app
        networks:
            - frontend
            - backend

    elk:
        container_name: elk
        build:
            context: ./src/images/elk/
        image: gpupo/container-orchestration:elk-latest
        ports:
            - "8080:80"
        volumes:
            - ./shared/elk/logstash:/etc/logstash
            - ./shared/elk/logstash/patterns:/opt/logstash/patterns
        networks:
            - frontend
            - backend

networks:
    frontend:
    backend:
