version: '3'
volumes:
    php:
        # driver: local-persist
        driver_opts:
            mountpoint: ./shared/
    logs:
        # driver: local-persist
        driver_opts:
            mountpoint: ./shared/
services:
    php:
        container_name: php-fpm
        build:
            context: ./src/images/php-fpm/
        image: container-orchestration/php-fpm:latest
        ports:
            - "9000:9000"
        volumes:
            - php:/var/www/app
            - php:/var/www/app/var/logs
    nginx:
        container_name: nginx
        build:
            context: ./src/images/nginx/
        image: container-orchestration/nginx:latest
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - logs:/var/log/nginx
            - php:/var/www/app
