apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml --provider openshift convert -o
      src/kompose/openshift/
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: elk
  name: elk
spec:
  replicas: 1
  selector:
    io.kompose.service: elk
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elk
    spec:
      containers:
      - image: ' '
        name: elk
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/logstash
          name: elk-data
        - mountPath: /opt/logstash/patterns
          name: elk-data
      restartPolicy: Always
      volumes:
      - name: elk-data
        persistentVolumeClaim:
          claimName: elk-data
      - name: elk-data
        persistentVolumeClaim:
          claimName: elk-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - elk
      from:
        kind: ImageStreamTag
        name: elk:elk-latest
    type: ImageChange
status: {}
