apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elk
  name: elk
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gpupo/container-orchestration:elk-latest
    generation: null
    importPolicy: {}
    name: elk-latest
status:
  dockerImageRepository: ""
