apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
      src/kompose/openshift/
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-upstream
  name: nginx-upstream
spec:
  replicas: 1
  selector:
    io.kompose.service: nginx-upstream
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-upstream
    spec:
      containers:
      - image: ' '
        name: nginx-upstream
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/logs/nginx
          name: logs-data
        - mountPath: /var/www/app
          name: app-data
      restartPolicy: Always
      volumes:
      - name: logs-data
        persistentVolumeClaim:
          claimName: logs-data
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nginx-upstream
      from:
        kind: ImageStreamTag
        name: nginx-upstream:nginx-upstream-latest
    type: ImageChange
status: {}
