apiVersion: v1
kind: Service
metadata:
  annotations:
      src/kompose/openshift/
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "15671"
    port: 15671
    targetPort: 15671
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
