apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: simpleHTTPServer
  name: simpleHTTPServer
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gpupo/container-orchestration:simpleHTTPServer-latest
    generation: null
    importPolicy: {}
    name: simpleHTTPServer-latest
status:
  dockerImageRepository: ""
