apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
      src/kompose/openshift/
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: simpleHTTPServer
  name: simpleHTTPServer
spec:
  replicas: 1
  selector:
    io.kompose.service: simpleHTTPServer
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: simpleHTTPServer
    spec:
      containers:
      - image: ' '
        name: simpleHTTPServer
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - simpleHTTPServer
      from:
        kind: ImageStreamTag
        name: simpleHTTPServer:simpleHTTPServer-latest
    type: ImageChange
status: {}
