apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: jackrabbit
  name: jackrabbit
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jackrabbit
    spec:
      containers:
      - env:
        - name: RABBIT_URL
          value: amqp://rabbitmq
        image: gpupo/container-orchestration:jackrabbit-latest
        name: jackrabbit
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
