apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-core
  name: nginx-core
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gpupo/container-orchestration:nginx-core-latest
    generation: null
    importPolicy: {}
    name: nginx-core-latest
status:
  dockerImageRepository: ""
