apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml --provider openshift convert -o
      src/openshift/kompose/
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-core
  name: nginx-core
spec:
  replicas: 1
  selector:
    io.kompose.service: nginx-core
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-core
    spec:
      containers:
      - image: ' '
        name: nginx-core
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nginx-core
      from:
        kind: ImageStreamTag
        name: nginx-core:nginx-core-latest
    type: ImageChange
status: {}
