apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gpupo/container-orchestration:php-latest
    generation: null
    importPolicy: {}
    name: php-latest
status:
  dockerImageRepository: ""
