version: '2'
services:
    php:
        build: ./images/php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./shared/app:/var/www/app:cached
            - ./shared/logs/app:/var/www/app/var/logs:cached
    nginx:
        build: ./images/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./shared/logs/nginx/:/var/log/nginx:cached
